import { test, expect } from '@playwright/test';
import { createStoryBranches, createStoryDocument } from '../../packages/story-domain/src/index';
import { createBlankStoryProject, insertStoryCut } from '../../packages/runtime-core/src/authoring';
import { readFileSync } from 'node:fs';

test('chapter identity and extended branch cuts survive editor, file export and reload',async({page})=>{
 let count=0;
 let project=createBlankStoryProject({id:'identity-e2e',chapterId:'intro',lineId:'start',title:'장과 갈래 구분'});
 project={...project,chapters:[{...project.chapters[0],chapterNumber:2,title:'갈림길'}]};
 project=createStoryBranches(project,'start',2,()=>`branch-${++count}`);
 const source=project.lines.find(line=>line.id==='start')!;
 if(source.flow?.type!=='choice')throw Error('missing branches');
 const [a,b]=source.flow.options;
 project=insertStoryCut(project,a.targetLineId!,'second-a');
 project={...project,lines:project.lines.map(line=>({...line,text:line.id==='second-a'?'A 갈래에서만 읽는 두 번째 컷':line.id===b.targetLineId?'B 갈래의 첫 컷':line.id==='start'?'어느 길로 갈까요?':'다시 만나는 곳'}))};
 const document=createStoryDocument({project,savedAt:'2026-10-07T00:00:00.000Z',appVersion:'chapter-test'});
 await page.goto('/?view=editor');await expect(page.getByTestId('save-status')).toHaveText('기기에 저장됨');
 const management=page.getByText('작품 관리',{exact:true});if(await management.isVisible())await management.evaluate(node=>{const d=node.closest('details');if(d)d.open=true;});
 await page.getByLabel('작품 파일 가져오기').setInputFiles({name:'chapter.knolstory',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(document))});
 await expect(page.getByTestId('save-status')).toHaveText('기기에 저장됨');
 await page.getByRole('button',{name:'이 장 대본',exact:true}).click();
 const panel=page.getByRole('region',{name:'이 장 대본',exact:true});
 await panel.getByText('장 설정 · 화자와 기본 자료',{exact:true}).click();
 await panel.getByLabel('장 번호',{exact:true}).fill('2');
 await panel.getByLabel('장 갈래 표시',{exact:true}).fill('');
 await expect(panel).toContainText('2장 · 갈림길');
 await page.getByRole('button',{name:'현재 컷 꾸미기',exact:true}).click();
 const cutButton=page.getByRole('button',{name:'컷 목록',exact:true});if(await cutButton.isVisible())await cutButton.click();
 await expect(page.getByRole('complementary',{name:'장과 컷 목록'})).toContainText('3장A');
 await expect(page.getByRole('complementary',{name:'장과 컷 목록'})).toContainText('3장B');
 await page.locator('[data-line-id="second-a"]').evaluate(node=>{node.closest('details')!.open=true;});
 await page.locator('[data-line-id="second-a"]').click();
 await page.getByRole('button',{name:'이 장 대본',exact:true}).click();
 await panel.getByText('장 설정 · 화자와 기본 자료',{exact:true}).click();
 await expect(panel.getByLabel('장 번호',{exact:true})).toHaveValue('3');
 await expect(panel.getByLabel('장 갈래 표시',{exact:true})).toHaveValue('A');
 await expect(panel.getByLabel('2컷 대사 / 해설')).toHaveValue('A 갈래에서만 읽는 두 번째 컷');
 await expect(page.getByTestId('save-status')).toHaveText('기기에 저장됨');
 await management.evaluate(node=>{node.closest('details')!.open=true;});
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'작품 파일 내보내기',exact:true}).click();
 const exported=JSON.parse(readFileSync((await(await download).path())!,'utf8')).project;
 expect(exported.chapters.slice(1).map((c:{chapterNumber:number;branchLabel?:string})=>[c.chapterNumber,c.branchLabel])).toEqual([[3,'A'],[3,'B'],[4,undefined]]);
 expect(exported.lines.find((l:{id:string})=>l.id===a.targetLineId).flow).toBeUndefined();
 expect(exported.lines.find((l:{id:string})=>l.id==='second-a').flow).toEqual(project.lines.find(l=>l.id==='second-a')?.flow);
 await page.reload();await expect(page.getByTestId('save-status')).toHaveText('기기에 저장됨');
 await page.getByRole('button',{name:'이 장 대본',exact:true}).click();
 await expect(panel).toContainText('3장A');
});
