import {test,expect,type Page} from '@playwright/test';
import {mkdirSync,readFileSync,writeFileSync} from 'node:fs';
const evidence='docs/architecture/evidence/creative-reading';
const title='숲의 약속 · 두 길에서 만나는 친구';
const background='seonnyeo.background.BG-forest-roots';
const actor='heungbu.character.heungbu-young';
const chapters=[
 {number:1,branch:'',title:'여행의 시작',texts:['아침 빛이 작은 숲을 깨웠다.','흥부는 친구에게 줄 선물을 챙겼다.','나는 흥부와 함께 숲 입구로 걸었다.']},
 {number:2,branch:'',title:'두 길 앞에서',texts:['숲 깊은 곳에서 두 길이 나타났다.','밝은 길에서는 새가 노래하고, 밤길에서는 별이 빛났다.','어느 길로 친구를 찾아갈까?']},
 {number:3,branch:'A',title:'햇빛의 길',texts:['햇빛 아래에서 작은 제비를 만났다.','제비가 알려 준 길을 따라 다리로 향했다.']},
 {number:3,branch:'B',title:'별빛의 길',texts:['별빛 아래에서 길 잃은 친구를 만났다.','우리는 서로 손을 잡고 다리로 향했다.']},
 {number:4,branch:'',title:'다시 만나는 다리',texts:['서로 다른 길을 지나 같은 다리에서 만났다.','다음 여행에서도 서로의 이야기를 듣기로 약속했다.']},
];
async function saved(page:Page){await expect(page.getByTestId('save-status')).toHaveText('기기에 저장됨');}
async function manage(page:Page){const summary=page.getByText('작품 관리',{exact:true});if(!await summary.locator('..').evaluate(n=>(n as HTMLDetailsElement).open))await summary.click();}
async function tool(page:Page,name:string){const button=page.getByRole('button',{name,exact:true});if(await button.isVisible())await button.click();}
async function id(page:Page){return (await page.locator('[data-line-id][aria-current="true"]').getAttribute('data-line-id'))!;}
async function select(page:Page,lineId:string){await page.getByRole('button',{name:'현재 컷 꾸미기',exact:true}).click();await tool(page,'컷 목록');const button=page.locator(`[data-line-id="${lineId}"]`);await button.evaluate(n=>{n.closest('details')!.open=true;});await button.click();}
async function pick(page:Page,label:string,asset:string){await page.getByRole('button',{name:`${label} 이미지 찾기`,exact:true}).click();const dialog=page.getByRole('dialog',{name:`이미지 선택 · ${label}`,exact:true});await dialog.getByLabel('이미지 검색').fill(asset===background?'폭풍이 지나간 숲':'흥부');await dialog.locator(`[data-asset-id="${asset}"]`).click();await dialog.getByRole('button',{name:'선택한 이미지 적용',exact:true}).click();}
async function exportFile(page:Page,path:string){await saved(page);await manage(page);const pending=page.waitForEvent('download');await page.getByRole('button',{name:'작품 파일 내보내기',exact:true}).click();await(await pending).saveAs(path);return JSON.parse(readFileSync(path,'utf8'));}
async function ready(page:Page){const status=page.getByTestId('story-runtime-status');await expect(status).toContainText('연결됨',{timeout:90000});await expect.poll(()=>status.evaluate(n=>n.getAttribute('data-scene-revision')===n.getAttribute('data-rendered-revision')),{timeout:30000}).toBe(true);await expect.poll(()=>page.evaluate(()=>{const viewport=document.querySelector('[data-testid="story-stage-viewport"]')!.getBoundingClientRect();const status=document.querySelector('[data-testid="story-runtime-status"]')!;const width=Number(status.getAttribute('data-scene-width')),height=Number(status.getAttribute('data-scene-height'));return Math.abs(width/height-viewport.width/viewport.height)<.02&&Number(status.getAttribute('data-engine-width'))===width&&Number(status.getAttribute('data-engine-height'))===height;}),{timeout:30000}).toBe(true);}
async function shot(page:Page,name:string){await page.screenshot({path:`${evidence}/${name}.png`});}
async function author(page:Page){
 await page.goto('/?view=editor');await saved(page);await manage(page);await page.getByRole('button',{name:'새 작품 만들기',exact:true}).click();await page.getByLabel('새 작품 제목').fill(title);await page.getByRole('button',{name:'빈 작품 시작',exact:true}).click();
 const groups:string[][]=[];
 for(const [chapterIndex,chapter] of chapters.entries()){
  if(chapterIndex===1||chapterIndex===4){await page.getByRole('button',{name:'현재 컷 꾸미기',exact:true}).click();await tool(page,'컷 목록');await page.getByRole('button',{name:'새 장 추가',exact:true}).click();}
  if(chapterIndex===2||chapterIndex===3){await select(page,groups[1]![2]!);await tool(page,'선택지 편집');await page.getByRole('button',{name:`선택지 ${chapterIndex-1}에 새 장 연결`,exact:true}).click();}
  await page.getByRole('button',{name:'이 장 대본',exact:true}).click();const writer=page.getByRole('region',{name:'이 장 대본',exact:true});const settings=writer.getByText('장 설정 · 화자와 기본 자료',{exact:true});if(!await settings.locator('..').evaluate(n=>(n as HTMLDetailsElement).open))await settings.click();
  if(chapter.branch){await expect(writer.getByLabel('장 번호',{exact:true})).toHaveValue('3');await expect(writer.getByLabel('장 갈래 표시',{exact:true})).toHaveValue(chapter.branch);}else{await writer.getByLabel('장 번호',{exact:true}).fill(String(chapter.number));await writer.getByLabel('장 갈래 표시',{exact:true}).fill('');}await writer.getByLabel('대본 장 제목').fill(chapter.title);await writer.getByLabel('장 개요').fill(`${chapter.number}장${chapter.branch}에서 친구를 만나는 이야기`);
  await writer.getByLabel('장 화자 추가').fill('흥부');await writer.getByRole('button',{name:'장 화자 등록',exact:true}).click();await pick(page,'장 기본 배경',background);await pick(page,'장 기본 왼쪽 인물',actor);
  if(chapterIndex===0){await writer.getByLabel('장 배경음 동작').selectOption('play');await writer.getByLabel('장 배경음 파일 등록').setInputFiles({name:'숲의-약속.wav',mimeType:'audio/wav',buffer:readFileSync('apps/web/public/assets/audio/forest.wav')});await expect(writer.getByLabel('장 배경음',{exact:true})).toHaveValue(/^audio:custom:/);}
  const cuts:string[]=[];
  for(const [cutIndex,text] of chapter.texts.entries()){
   if(cutIndex)await writer.getByRole('button',{name:'대사 컷 추가',exact:true}).click();cuts.push(await id(page));await writer.getByLabel(`${cutIndex+1}컷 대사 / 해설`).fill(text);await writer.getByLabel(`${cutIndex+1}컷 글 종류`).selectOption(cutIndex===0?'narration':'dialogue');if(cutIndex)await writer.getByLabel(`${cutIndex+1}컷 화자`).selectOption('흥부');
  }
  groups.push(cuts);
  if(chapterIndex===1){await select(page,cuts[2]!);await tool(page,'선택지 편집');await page.getByLabel('진행 방식').selectOption('choice');await page.getByLabel('선택지 1 문구').fill('햇빛의 길로 가기');await page.getByLabel('선택지 2 문구').fill('별빛의 길로 가기');}
 }
 // Complete existing links with the authoring controls; no fixture/IDB project seeding.
 for(const [from,to] of [[groups[0]![2],groups[1]![0]],[groups[2]![1],groups[4]![0]],[groups[3]![1],groups[4]![0]]]){await select(page,from!);await tool(page,'선택지 편집');await page.getByLabel('진행 방식').selectOption('goto');await page.getByLabel('도착 컷',{exact:true}).selectOption(to!);}
 await select(page,groups[4]![1]!);await tool(page,'선택지 편집');await page.getByLabel('진행 방식').selectOption('ending');
 await select(page,groups[0]![0]!);await tool(page,'자산 편집');await pick(page,'왼쪽 인물',actor);await page.getByLabel(/ 크기 배율$/).first().fill('0.9');await page.getByLabel(/ 가로 위치$/).first().fill('32');
 await tool(page,'연출 편집');await page.getByRole('button',{name:'효과음 추가',exact:true}).click();await page.getByLabel('1번 효과음 파일 등록').setInputFiles({name:'약속의-종.wav',mimeType:'audio/wav',buffer:readFileSync('apps/web/public/assets/audio/chime.wav')});await expect(page.getByLabel('1번 효과음',{exact:true})).toHaveValue(/^audio:custom:/);await page.getByLabel('효과',{exact:true}).selectOption('shake');await page.getByLabel('효과 대상').selectOption('background');await page.getByLabel('효과 적용 범위').selectOption('following');await page.getByLabel('효과 강도').selectOption('soft');
 await select(page,groups[1]![0]!);await tool(page,'연출 편집');await page.getByLabel('이어지는 효과 끝내기').check();await saved(page);await shot(page,'authoring-scope');for(const cuts of groups){await select(page,cuts[1]!);await tool(page,'자산 편집');await page.getByLabel('왼쪽 인물',{exact:true}).selectOption(actor);await tool(page,'글 편집');await page.getByLabel('말하는 위치',{exact:true}).selectOption('left');}await select(page,groups[1]![2]!);await tool(page,'선택지 편집');await shot(page,'authoring-choice-links');await page.getByRole('button',{name:'전체 흐름 보기',exact:true}).click();await shot(page,'authored-flow');await page.keyboard.press('Escape');
 return groups;
}

test('UI-authored twelve-cut story survives Chrome files and both actual RenPy reading paths',async({playwright},info)=>{
 test.skip(info.project.name!=='stories-runtime');test.setTimeout(480000);mkdirSync(evidence,{recursive:true});
 const browser=await playwright.chromium.launch({channel:'chrome'});const context=await browser.newContext({viewport:{width:1280,height:900}});const page=await context.newPage();page.setDefaultTimeout(15000);
 try{
  const groups=await author(page);const path=`${evidence}/forest-promise.knolstory`;const original=await exportFile(page,path);expect(original.project.lines).toHaveLength(12);expect(original.project.chapters.map((c:{chapterNumber:number;branchLabel?:string})=>[c.chapterNumber,c.branchLabel??''])).toEqual([[1,''],[2,''],[3,'A'],[3,'B'],[4,'']]);expect(original.audioResources.length).toBe(2);
  await page.reload();await saved(page);expect(await exportFile(page,path)).toMatchObject({project:original.project,audioResources:original.audioResources});
  const fresh=await browser.newContext({viewport:{width:1280,height:900},hasTouch:true});const reading=await fresh.newPage();reading.setDefaultTimeout(15000);await reading.goto('http://127.0.0.1:3000/?view=editor');await saved(reading);await manage(reading);await reading.getByLabel('작품 파일 가져오기').setInputFiles(path);await saved(reading);expect(await exportFile(reading,info.outputPath('fresh.knolstory'))).toMatchObject({project:original.project,audioResources:original.audioResources});await reading.getByLabel('화면 구도').selectOption('auto');
  await reading.getByRole('button',{name:'처음부터 읽기',exact:true}).click();await ready(reading);const frame=reading.getByTestId('story-runtime-frame');await frame.evaluate(n=>n.setAttribute('data-journey-instance','same'));
  const box=(await frame.boundingBox())!;await reading.touchscreen.tap(box.x+box.width*.5,box.y+box.height*.1);await ready(reading);await expect(reading.getByTestId('story-runtime-status')).toHaveAttribute('data-audio-unlocked','true');
  const status=reading.getByTestId('story-runtime-status');const soundBefore=await status.getAttribute('data-sound-play-count');const musicBefore=await status.getAttribute('data-music-start-count');await reading.getByRole('button',{name:'전체 화면',exact:true}).click();await expect.poll(()=>reading.evaluate(()=>!!document.fullscreenElement)).toBe(true);await expect(frame).toHaveAttribute('data-journey-instance','same');await reading.getByRole('button',{name:'전체 화면 해제',exact:true}).click();await expect.poll(()=>reading.evaluate(()=>!!document.fullscreenElement)).toBe(false);await ready(reading);await reading.getByRole('button',{name:'읽기 저장',exact:true}).click();await reading.getByRole('region',{name:'1번 읽기 저장'}).getByRole('button',{name:'여기에 저장'}).click();await expect(reading.getByRole('region',{name:'1번 읽기 저장'})).toContainText(chapters[0]!.texts[0]!);await shot(reading,'reading-save');await reading.getByRole('button',{name:'읽기 메뉴 닫기'}).click();await expect(status).toHaveAttribute('data-sound-play-count',soundBefore!);await expect(status).toHaveAttribute('data-music-start-count',musicBefore!);
  for(const [width,height,name] of [[1280,900,'desktop'],[844,390,'phone-landscape'],[390,844,'phone-portrait']] as const){await reading.setViewportSize({width,height});await ready(reading);await expect(frame).toHaveAttribute('data-journey-instance','same');await shot(reading,`reading-${name}`);expect(await reading.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
  await reading.getByRole('button',{name:'다음으로',exact:true}).focus();await reading.keyboard.press('Enter');await ready(reading);await shot(reading,'reading-phone-portrait-speaker');await reading.getByRole('button',{name:'읽기 불러오기',exact:true}).click();await reading.getByRole('region',{name:'1번 읽기 저장'}).getByRole('button',{name:'불러오기',exact:true}).click();await ready(reading);await reading.setViewportSize({width:1280,height:900});await ready(reading);
  for(const branch of [0,1]){
   if(branch){await reading.getByRole('button',{name:'읽기 불러오기',exact:true}).click();await reading.getByRole('region',{name:'1번 읽기 저장'}).getByRole('button',{name:'불러오기',exact:true}).click();await ready(reading);}
   for(let n=0;n<5;n++){const next=reading.getByRole('button',{name:'다음으로',exact:true});if(n===0){await next.focus();await reading.keyboard.press('Enter');}else await next.click();await ready(reading);}
   await expect(reading.getByTestId('playback-status')).toHaveText('선택해 주세요');if(!branch){for(const [width,height,name] of [[1280,900,'desktop'],[844,390,'landscape'],[390,844,'portrait']] as const){await reading.setViewportSize({width,height});await ready(reading);await shot(reading,`reading-choice-${name}`);}await reading.setViewportSize({width:1280,height:900});await ready(reading);}await reading.getByRole('button',{name:branch?'별빛의 길로 가기':'햇빛의 길로 가기',exact:true}).click();await ready(reading);await saved(reading);const branchState=await reading.evaluate(()=>JSON.parse(localStorage.getItem('knolstory-next-workspace-v1')!).playback);for(const size of [{width:844,height:390},{width:390,height:844},{width:1280,height:900}]){await reading.setViewportSize(size);await ready(reading);await saved(reading);expect(await reading.evaluate(()=>JSON.parse(localStorage.getItem('knolstory-next-workspace-v1')!).playback)).toEqual(branchState);}await reading.getByRole('button',{name:'전체 화면',exact:true}).click();await expect.poll(()=>reading.evaluate(()=>!!document.fullscreenElement)).toBe(true);await reading.getByRole('button',{name:'전체 화면 해제',exact:true}).click();await ready(reading);await saved(reading);expect(await reading.evaluate(()=>JSON.parse(localStorage.getItem('knolstory-next-workspace-v1')!).playback)).toEqual(branchState);await expect(frame).toHaveAttribute('data-journey-instance','same');
   for(let n=0;n<3;n++){await reading.getByRole('button',{name:'다음으로',exact:true}).click();await ready(reading);}
   await reading.getByRole('button',{name:'지난 기록',exact:true}).click();const log=reading.getByRole('dialog',{name:'지난 기록'});await expect(log).toContainText(chapters[branch+2]!.texts[0]!);await expect(log).not.toContainText(chapters[branch?2:3]!.texts[0]!);await log.locator('li').nth(5).scrollIntoViewIfNeeded();await shot(reading,`read-path-${branch?'B':'A'}`);await reading.getByRole('button',{name:'읽기 메뉴 닫기'}).click();await reading.getByRole('button',{name:'다음으로',exact:true}).click();await expect(reading.getByTestId('playback-status')).toHaveText('이야기 끝');
  }
  await reading.getByRole('button',{name:'지난 기록',exact:true}).click();await reading.getByRole('dialog',{name:'지난 기록'}).getByRole('button',{name:'이 지점부터 읽기'}).nth(5).click();await ready(reading);await expect(reading.getByTestId('playback-status')).toHaveText('선택해 주세요');await reading.getByRole('button',{name:'햇빛의 길로 가기',exact:true}).click();await ready(reading);
  await reading.getByRole('button',{name:'편집으로',exact:true}).click();await select(reading,groups[0]![1]!);await tool(reading,'글 편집');await reading.getByLabel('대사 / 해설',{exact:true}).fill('흥부는 친구에게 줄 선물과 편지를 챙겼다.');await saved(reading);await reading.getByRole('button',{name:'현재 컷부터 읽기',exact:true}).click();await ready(reading);await expect(reading.getByText('흥부는 친구에게 줄 선물과 편지를 챙겼다.',{exact:true})).toBeVisible();await expect(frame).toHaveAttribute('data-journey-instance','same');await shot(reading,'edited-native-reading');await reading.getByRole('button',{name:'처음부터 읽기',exact:true}).click();await ready(reading);await expect(reading.getByText(chapters[0]!.texts[0]!,{exact:true})).toBeVisible();await expect(frame).toHaveAttribute('data-journey-instance','same');
  writeFileSync(`${evidence}/run-summary.json`,JSON.stringify({browser:await browser.version(),authorship:'Created from blank story using UI controls; no seeded project',cutCount:12,chapters:['1','2','3A','3B','4'],routes:['A → 4','B → 4'],checks:['reload','export','isolated-context import','native audio unlock','save/load','actual-path history','history reselection','desktop/phone-landscape/phone-portrait','touch','keyboard Enter','fullscreen enter/exit','menu preserves audio counts','restart','portrait speaker','edit return'],hardware:'Chrome viewport conditions only; no Android hardware claim'},null,2));await fresh.close();
 }finally{await context.close();await browser.close();}
});
