import {test,expect,type Page} from '@playwright/test';
import {mkdirSync,writeFileSync} from 'node:fs';
import {enterLibrary,beginSelectedBook,openBuiltinEdition,builtinEditions} from './library-entry';
const evidence='docs/architecture/evidence/four-work-library';
async function ready(page:Page){const status=page.getByTestId('story-runtime-status');await expect(status).toContainText('연결됨',{timeout:90000});await expect.poll(()=>status.evaluate(n=>n.getAttribute('data-rendered-revision')===n.getAttribute('data-scene-revision')),{timeout:30000}).toBe(true);}
async function stored(page:Page){return page.evaluate(()=>JSON.parse(localStorage.getItem('knolstory-next-workspace-v1')!));}
test('four books retain eight independent native reading paths and manual save slots across reload',async({page},info)=>{
 test.skip(info.project.name!=='stories-runtime');test.setTimeout(480000);mkdirSync(evidence,{recursive:true});await page.goto('/');await enterLibrary(page);await expect(page.locator('article[data-work-id]')).toHaveCount(4);
 const records:Array<{workId:string;edition:string;key:string;projectId:string;lineId:string;path:string[]}> = [];
 for(const [index,[workId,edition]] of builtinEditions.entries()){
  await openBuiltinEdition(page,workId,edition);await beginSelectedBook(page);await ready(page);
  const frame=page.getByTestId('story-runtime-frame');if(index===0)await frame.evaluate(n=>n.setAttribute('data-four-work-instance','same'));else await expect(frame).toHaveAttribute('data-four-work-instance','same');
  const rect=(await frame.boundingBox())!;await page.mouse.click(rect.x+rect.width*.5,rect.y+rect.height*.1);await ready(page);
  for(let step=0;step<(edition==='original'?2:3);step++){await expect(page.getByRole('button',{name:'다음으로',exact:true})).toBeEnabled({timeout:20000});await page.getByRole('button',{name:'다음으로',exact:true}).click();await ready(page);}
  await page.getByRole('button',{name:'읽기 저장',exact:true}).click();await page.getByRole('region',{name:'1번 읽기 저장',exact:true}).getByRole('button',{name:'여기에 저장',exact:true}).click();await page.getByRole('button',{name:'읽기 메뉴 닫기',exact:true}).click();await expect(page.getByTestId('save-status')).toHaveText('기기에 저장됨');
  const value=await stored(page);records.push({workId,edition,key:value.storyId,projectId:value.document.project.id,lineId:value.playback.lineId,path:value.playback.path});
  await page.getByRole('button',{name:'서재로',exact:true}).click();await expect(page.locator('article[data-work-id]')).toHaveCount(4);
 }
 expect(new Set(records.map(record=>record.projectId)).size).toBe(8);expect(new Set(records.map(record=>record.key)).size).toBe(8);
 await page.reload();await enterLibrary(page);
 for(const record of records){await openBuiltinEdition(page,record.workId,record.edition as 'original'|'knolstory','resume');await beginSelectedBook(page,true);await ready(page);const value=await stored(page);expect(value.storyId).toBe(record.key);expect(value.playback.lineId).toBe(record.lineId);expect(value.playback.path).toEqual(record.path);await page.getByRole('button',{name:'읽기 불러오기',exact:true}).click();await page.getByRole('region',{name:'1번 읽기 저장',exact:true}).getByRole('button',{name:'불러오기',exact:true}).click();await ready(page);expect((await stored(page)).playback.path).toEqual(record.path);await page.getByRole('button',{name:'서재로',exact:true}).click();}
 const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('knolstory-player-v1')!));for(const record of records){expect(saved.works[record.projectId]['1'].playback.path).toEqual(record.path);expect(saved.works[record.projectId]['1'].projectId).toBe(record.projectId);}
 await page.screenshot({path:`${evidence}/four-books-independent-resume.png`,fullPage:true});writeFileSync(`${evidence}/edition-resume-isolation.json`,JSON.stringify({records,manualSlotsIndependent:true,runtimePersistedAcrossEditionSwitches:true},null,2));
});

test('reading an original then editing the current cut creates a preserved personal copy',async({page},info)=>{
 test.skip(info.project.name!=='stories-runtime');test.setTimeout(180000);mkdirSync(evidence,{recursive:true});await page.goto('/');await enterLibrary(page);await openBuiltinEdition(page,'rabbit','original');await beginSelectedBook(page);await ready(page);
 const rect=(await page.getByTestId('story-runtime-frame').boundingBox())!;await page.mouse.click(rect.x+rect.width*.5,rect.y+rect.height*.1);await expect(page.getByRole('button',{name:'다음으로',exact:true})).toBeEnabled({timeout:20000});await page.getByRole('button',{name:'다음으로',exact:true}).click();await ready(page);await expect(page.getByTestId('save-status')).toHaveText('기기에 저장됨');const before=await stored(page),original=before.document.project;
 await page.getByRole('button',{name:'편집으로',exact:true}).click();await expect(page.getByLabel('대사 / 해설',{exact:true})).toBeVisible();await expect.poll(async()=>(await stored(page)).storyId).toMatch(/^new:/);await expect(page.getByTestId('save-status')).toHaveText('기기에 저장됨');const after=await stored(page);expect(after.storyId).toMatch(/^new:/);expect(after.lineId).toBe(before.playback.lineId);expect(after.document.project.id).not.toBe(original.id);expect(after.document.project.lines).toEqual(original.lines);expect(after.document.project.chapters).toEqual(original.chapters);expect(after.works[before.storyId].project).toEqual(original);
 const cut=original.lines.find((line:{id:string})=>line.id===before.playback.lineId);await expect(page.getByLabel('대사 / 해설',{exact:true})).toHaveValue(cut.text);await page.getByLabel('대사 / 해설',{exact:true}).fill('원본을 지키고 내 문장으로 고쳐 씁니다.');await expect.poll(async()=>(await stored(page)).document.project.lines.find((line:{id:string})=>line.id===cut.id).text).toBe('원본을 지키고 내 문장으로 고쳐 씁니다.');await expect(page.getByTestId('save-status')).toHaveText('기기에 저장됨');const edited=await stored(page);expect(edited.works[before.storyId].project).toEqual(original);expect(edited.document.project.lines.find((line:{id:string})=>line.id===cut.id).text).toBe('원본을 지키고 내 문장으로 고쳐 씁니다.');await page.reload();await expect(page.getByLabel('대사 / 해설',{exact:true})).toHaveValue('원본을 지키고 내 문장으로 고쳐 씁니다.');expect((await stored(page)).works[before.storyId].project).toEqual(original);
 await page.getByRole('button',{name:'서재로',exact:true}).click();await openBuiltinEdition(page,'rabbit','original','resume');await beginSelectedBook(page,true);await ready(page);expect((await stored(page)).playback.lineId).toBe(cut.id);expect((await stored(page)).document.project).toEqual(original);await expect(page.getByText(cut.text,{exact:true})).toBeVisible();writeFileSync(`${evidence}/read-to-edit-original-preservation.json`,JSON.stringify({sourceKey:before.storyId,sourceProjectId:original.id,copyProjectId:after.document.project.id,currentCut:cut.id,sourceProjectExactMatch:true},null,2));
});

test('personal book deletion needs confirmation and survives reload in recoverable storage',async({page},info)=>{
 test.skip(info.project.name!=='host');page.setDefaultTimeout(10000);await page.goto('/');await enterLibrary(page);await openBuiltinEdition(page,'seonnyeo','original','prepare');await expect.poll(async()=>(await stored(page)).storyId).toMatch(/^new:/);await expect(page.getByTestId('preparation-save-status')).toHaveText('기기에 저장됨');const before=await stored(page);await page.getByRole('button',{name:'서재로',exact:true}).click();const own=page.getByRole('article',{name:`내 작품 · ${before.document.project.title}`,exact:true});
 async function requestDelete(){await own.getByRole('button',{name:/책 표지와 소개 보기$/}).click();await page.getByRole('dialog').locator('summary').filter({hasText:'책 꾸미기·작품 도구'}).click();await page.getByRole('dialog').getByRole('button',{name:'내 작품 삭제',exact:true}).click();}
 await requestDelete();await expect(page.getByRole('dialog',{name:'내 작품 삭제 확인'})).toBeVisible();await page.getByRole('dialog',{name:'내 작품 삭제 확인'}).getByRole('button',{name:'취소',exact:true}).click();await expect(own).toBeVisible();await page.keyboard.press('Escape');await requestDelete();await page.getByRole('dialog',{name:'내 작품 삭제 확인'}).getByRole('button',{name:'삭제 확인',exact:true}).click();await expect(own).toHaveCount(0);await page.reload();await enterLibrary(page);await expect(own).toHaveCount(0);await page.getByText('삭제한 작품 복구',{exact:true}).click();await page.getByRole('button',{name:`${before.document.project.title} 복구`,exact:true}).click();await expect(own).toBeVisible();expect((await stored(page)).works[before.storyId].project).toEqual(before.document.project);await expect(page.locator('article[data-work-id]')).toHaveCount(4);
});
