import {enterLibrary,beginSelectedBook} from './library-entry';
import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
test('existing-work audio source and rights records travel with the original bytes',async({page,browser})=>{
 await page.goto('/?view=editor');await expect(page.getByTestId('save-status')).toHaveText('기기에 저장됨');await page.getByRole('button',{name:'효과음 추가',exact:true}).click();
 await page.getByLabel('1번 효과음 파일 등록',{exact:true}).setInputFiles({name:'출처기록-검사.wav',mimeType:'audio/wav',buffer:readFileSync('apps/web/public/assets/audio/chime.wav')});await expect(page.getByLabel('1번 효과음',{exact:true})).toHaveValue(/^audio:custom:/);
 await page.getByText('1번 효과음 출처·이용 조건 기록',{exact:true}).click();await page.getByLabel('1번 효과음 제공처',{exact:true}).fill('검증용 원본 제작');await page.getByLabel('1번 효과음 라이선스',{exact:true}).fill('CC-BY-NC-4.0');await page.getByLabel('1번 효과음 생성 당시 요금제',{exact:true}).fill('무료 조건 기록 검사');await page.getByLabel('1번 효과음 필요한 출처 표시',{exact:true}).fill('검증 자료 제작자와 라이선스 표시');await page.getByLabel('1번 효과음 재배포 조건',{exact:true}).selectOption('permitted');await page.getByLabel('1번 효과음 상업 이용 조건',{exact:true}).selectOption('restricted');await page.getByRole('button',{name:'출처 기록 저장',exact:true}).click();await expect(page.getByText('출처 기록을 음원과 함께 보관했습니다. 작품 파일에도 포함됩니다.',{exact:true})).toBeVisible();
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'작품 파일 내보내기',exact:true}).click();const path=(await(await download).path())!;const archive=JSON.parse(readFileSync(path,'utf8'));expect(archive.audioResources[0].provenance).toMatchObject({provider:'검증용 원본 제작',commercialUse:'restricted',redistribution:'permitted',generationPlan:'무료 조건 기록 검사'});
 const clean=await browser.newContext();const fresh=await clean.newPage();await fresh.goto('/?view=editor');await expect(fresh.getByTestId('save-status')).toHaveText('기기에 저장됨');await fresh.getByLabel('작품 파일 가져오기',{exact:true}).setInputFiles(path);await expect(fresh.getByTestId('save-status')).toHaveText('기기에 저장됨');const restored=fresh.waitForEvent('download');await fresh.getByRole('button',{name:'작품 파일 내보내기',exact:true}).click();expect(JSON.parse(readFileSync((await(await restored).path())!,'utf8')).audioResources).toEqual(archive.audioResources);await clean.close();
});
