import { test, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';
test('ShortStory edits static pages, saves, restores files and prints without runtime', async ({page}) => {
 await page.goto('/shortstory');
 await expect(page.getByRole('heading',{name:'숏스토리 그림책'})).toBeVisible();
 await page.getByLabel('이야기 제목',{exact:true}).fill('내 그림책');
 await page.getByLabel('이 쪽의 이야기').fill('첫 번째 그림의 이야기');
 await page.getByRole('button',{name:'현재 쪽 뒤에 빈 쪽 추가'}).click();
 await page.getByLabel('이 쪽 제목').fill('두 번째 쪽');
 await page.getByLabel('이 쪽의 이야기').fill('다음 장면입니다.');
 await page.getByRole('button',{name:'이 기기에 저장',exact:true}).click();
 await page.reload();
 await expect(page.getByLabel('이야기 제목',{exact:true})).toHaveValue('내 그림책');
 await page.getByRole('button',{name:'읽기',exact:true}).click();
 await expect(page.getByRole('region',{name:'숏스토리 읽기'})).toContainText('첫 번째 그림의 이야기');
 await page.getByRole('button',{name:'다음 쪽',exact:true}).click();
 await expect(page.getByRole('region',{name:'숏스토리 읽기'})).toContainText('다음 장면입니다.');
 const downloadEvent=page.waitForEvent('download');await page.getByRole('button',{name:'.shortstory로 보관'}).click();
 const download=await downloadEvent;expect(download.suggestedFilename()).toBe('내 그림책.shortstory');
 const path=await download.path();expect(path).toBeTruthy();
 await page.getByRole('button',{name:'새 그림책'}).click();
 await page.locator('input[type=file]').setInputFiles(path!);
 await expect(page.getByLabel('이야기 제목',{exact:true})).toHaveValue('내 그림책');
 await expect(page.locator('iframe')).toHaveCount(0);
 await page.emulateMedia({media:'print'});await expect(page.locator('[data-shortstory-print]')).toBeVisible();
 await expect(page.locator('[data-shortstory-print] article')).toHaveCount(3);
});
test('ShortStory pictures and Excel survive reopening on phone; unsupported audio is rejected', async ({page}) => {
 await page.setViewportSize({width:390,height:844});await page.goto('/shortstory');
 await page.getByText('이 쪽 그림 고르기',{exact:true}).click();
 const bg=page.getByLabel('쪽 배경',{exact:true});const id=await bg.locator('option').nth(1).getAttribute('value');expect(id).toBeTruthy();await bg.selectOption(id!);
 await expect(page.getByRole('img',{name:'1쪽 삽화',exact:true}).locator('img')).toHaveCount(1);
 await page.getByLabel('이 쪽의 이야기').fill('그림과 글을 엑셀로 보관해요.');
 const nextDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Excel로 보관',exact:true}).click();const saved=await nextDownload;const path=await saved.path();
 await page.getByRole('button',{name:'새 그림책'}).click();await page.locator('input[type=file]').setInputFiles({name:saved.suggestedFilename(),mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:await readFile(path!)});
 await expect(page.getByLabel('이 쪽의 이야기')).toHaveValue('그림과 글을 엑셀로 보관해요.');
 await page.getByText('이 쪽 그림 고르기',{exact:true}).click();await expect(page.getByLabel('쪽 배경',{exact:true})).toHaveValue(id!);
 await page.getByRole('button',{name:'이 기기에 저장',exact:true}).click();
 const project=await page.evaluate(()=>JSON.parse(localStorage.getItem('knolstory-shortstory-workspace-v1')!).project);
 await page.locator('input[type=file]').setInputFiles({name:'unsupported.shortstory',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({manifest:{format:'shortstory',version:1,kind:'project'},project:{...project,music:{assetId:'fake'}}}))});
 await expect(page.locator('main [role=alert]')).toContainText('숏스토리');await expect(page.getByLabel('이 쪽의 이야기')).toHaveValue('그림과 글을 엑셀로 보관해요.');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
});
